### PR TITLE
Add new param "enableDisqus" and fix some issues with README.md and exampleSite/config.toml

### PR DESCRIPTION
**Pull request by dataCobra**
Disable Disqus for specific content types is really good. But I would like it even more, if there is a param for fully disable or enable Disqus. It gives me more control over the third-party features I want to use. Because enabled third-party features are horrible to manage with GDPR.

Also I made the README.md file max textwidth to 78 so it is better to manage in texteditors and add the new information for "enableDisqus". 

In the exampleSite/config.toml I found some path issues that don't comply with the README.md, so I fixed them too.

### CODE REVIEW

**Comment by dataCobra** [comment]
I also added multilingual support for the static strings now. Please read the commit text to get more information about this commit.

**Comment by dataCobra** [comment]
I made some huge changes to the whole theme. The "base" is still the same but I've changed a lot of CSS and HTML for a better responsive experience and I got rid of the feathericons that where implemented via js and also got loaded via web. The theme uses FontAwesome now locally, so no third-party site is involved. Also I got rid of the third-party googlefonts and replaced it with variants of Roboto(-Slab) that are also locally installed.

**Comment by knadh** [comment]
Ah, Inter + Playfair define the aesthetics of Ink. Changing those are essentially creating a new theme. I previewed the PR but I prefer the existing look and feel.

Since this is a very large PR with many unrelated changes, it's difficult to review. For instance, I'm not sure why H1 for the page title has become H2 [here](https://github.com/knadh/hugo-ink/pull/5/files#diff-0de805c40330c8294640ec22490dc9ffL9).

Fine grained improvements can be merged though if you send smaller PR's.

Thanks!

**Comment by dataCobra** [comment]
I totally understand your decision. The pull request is really way to big. My knowledge in dealing with Git is unfortunately still very limited, which is why I still have a hard time with pull requests.

I was thinking about the part "the aesthetics of Ink" of your sentence. Ink is your theme and I really don't want to destroy the feel of it. That's why I'm thinking about doing my fully own theme with the fork of your great theme. 

If I make changes that are good also for your theme, I will share them with you if you like.

**Comment by knadh** [comment]
All good @dataCobra :) I'll close this PR. Please feel free to send smaller PRs with fixes and improvements that you make.

**Pull request closed without merging**
