### PR TITLE
Add support for LaTex.

### PR DESCRIPTION
**Pull request by agile6v**

### CODE REVIEW

**Comment by knadh** [comment]
Thanks, but since this is easy enough to add and only a tiny fraction of users would need LaTeX rendering, I think it's best not to merge this into the core.

**Comment by agile6v** [comment]
> Thanks, but since this is easy enough to add and only a tiny fraction of users would need LaTeX rendering, I think it's best not to merge this into the core.

Hi, @knadh Thank you for your reply. 

From my point of view, it's not a question of easy or hard. If I as a user I would like to have functionality out of the box rather than customizing it. Functionalities submitted by others have the same problem.  Of course, it also depends on where you want it to go.

Thanks again.

**Comment by knadh** [comment]
Thanks, I understand. But, best to keep the generic core of the theme as unencumbered as possible is my view.

**Comment by agile6v** [comment]
> Thanks, I understand. But, best to keep the generic core of the theme as unencumbered as possible is my view.

Closing.

**Pull request closed without merging**
