### PR TITLE
Add multilingual month support

### PR DESCRIPTION
**Pull request by dataCobra**
At the time of this writing, Go does not yet have support for
internationalized locales for dates, if you create a month.yaml in your data/
folder with a content like shown below. It will work.

1: "janvier"
2: "février"
3: "mars"
4: "avril"
5: "mai"
6: "juin"
7: "juillet"
8: "août"
9: "septembre"
10: "octobre"
11: "novembre"
12: "décembre"

### CODE REVIEW

**Comment by knadh** [comment]
Wouldn't a better approach be to use something like https://github.com/goodsign/monday?

The downside of having a map for months is that it's arbitrary and works for only months. What about weekday names?

**Comment by dataCobra** [comment]
I think the way of using a file and place it in the data/ folder is easier and more customizable. It is not bloated like a full translator written in Go. With this approach the user has full control over the names, could use fantasy names also.

For the weekdays there could be a weekdays.yaml in the future that give the feature of fully customizable weekdays.

**Comment by dataCobra** [comment]
I would find it very good, if the theme is as minimalistic as possible.

**Comment by dataCobra** [comment]
> I think the way of using a file and place it in the data/ folder is easier and more customizable. It is not bloated like a full translator written in Go. With this approach the user has full control over the names, could use fantasy names also.
> 
> For the weekdays there could be a weekdays.yaml in the future that give the feature of fully customizable weekdays.

Well after thinking about the weekdays. It is not so simple to add this feature.

The theme is using names currently only for the months, so I feel like adding the month feature
is no disadvantage for the theme. :+1:

**Comment by dataCobra** [comment]
I've tried to make a new pull request for my second commit. But for some reason it is now also in this pull request. I hope you don't mind.

**Pull request merged**
